import { useState } from "react";

const C = {
  bg:"#060809", card:"#0D1219", border:"#162028",
  red:"#E11D48", yellow:"#F59E0B", green:"#059669",
  blue:"#0EA5E9", purple:"#8B5CF6", orange:"#EA580C",
  teal:"#0D9488", text:"#E2EBF4", muted:"#384A5C", soft:"#6B8BA8",
};

function Tag(props) {
  var c = props.color || C.red;
  return (
    <span style={{
      background:c+"1A", color:c, border:"1px solid "+c+"45",
      padding:"2px 10px", borderRadius:4, fontSize:11, fontWeight:700,
      letterSpacing:0.8, textTransform:"uppercase", fontFamily:"monospace",
    }}>{props.label}</span>
  );
}

function Box(props) {
  return (
    <div style={{
      background:C.card, border:"1px solid "+C.border, borderRadius:14, padding:20,
      boxShadow:props.glow?"0 0 30px "+props.glow+"18":"none",
      ...props.style,
    }}>{props.children}</div>
  );
}

function STitle(props) {
  var c = props.color || C.red;
  return (
    <div style={{ marginBottom:26 }}>
      <div style={{ display:"flex", alignItems:"center", gap:14, marginBottom:8 }}>
        <div style={{ width:48, height:48, borderRadius:12, background:c+"15", border:"2px solid "+c+"45", display:"flex", alignItems:"center", justifyContent:"center", fontSize:26, flexShrink:0 }}>{props.icon}</div>
        <h2 style={{ margin:0, fontSize:22, color:C.text, fontWeight:700, letterSpacing:2 }}>{props.title}</h2>
      </div>
      {props.sub && <p style={{ margin:"0 0 0 62px", color:C.soft, fontSize:13, fontFamily:"monospace" }}>{props.sub}</p>}
      <div style={{ height:2, background:"linear-gradient(90deg,"+c+"80,transparent)", marginTop:12 }} />
    </div>
  );
}

function DataTable(props) {
  var hl = props.hi || [];
  var cols = props.cols || [C.soft, C.red, C.blue, C.yellow, C.green, C.orange];
  return (
    <div style={{ overflowX:"auto" }}>
      <table style={{ width:"100%", borderCollapse:"collapse", fontSize:13 }}>
        <thead>
          <tr style={{ background:"#090C10" }}>
            {props.heads.map(function(h,i) {
              return <th key={i} style={{ padding:"10px 14px", textAlign:i===0?"left":"center", color:cols[i]||C.soft, borderBottom:"2px solid "+C.border, fontFamily:"monospace", fontSize:11, letterSpacing:1 }}>{h}</th>;
            })}
          </tr>
        </thead>
        <tbody>
          {props.rows.map(function(row,ri) {
            return (
              <tr key={ri} style={{ background:hl.includes(ri)?C.red+"08":"transparent", borderBottom:"1px solid "+C.border+"40" }}>
                {row.map(function(cell,ci) {
                  return <td key={ci} style={{ padding:"9px 14px", textAlign:ci===0?"left":"center", color:ci===0?C.soft:C.text, fontFamily:ci===0?"monospace":"inherit", fontSize:ci===0?11:13, fontWeight:hl.includes(ri)?600:400 }}>{cell}</td>;
                })}
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

// ── DATA ──
var QS = [
  {
    id:1, level:"BASIC", topic:"Brake Types",
    q:"In a disc brake system, braking force is generated by pressing brake pads against the:",
    opts:["Brake drum inner surface","Rotating disc (rotor) on both sides","Tyre surface directly","Axle shaft"],
    ans:1,
    exp:"In disc brakes, the brake CALIPER houses pistons that press friction PADS against BOTH SIDES of a rotating disc (rotor) bolted to the wheel hub. Hydraulic pressure pushes the piston, pads clamp the disc, and friction converts kinetic energy to heat.\n\nIn drum brakes: Wheel CYLINDER pushes brake SHOES outward against the inside cylindrical surface of a drum fixed to the wheel.",
    tip:"Disc = pads clamp a DISC from both sides. Drum = shoes press outward against inside of DRUM. Disc brakes use PADS, drum brakes use SHOES. Remember this fundamental difference.",
  },
  {
    id:2, level:"BASIC", topic:"Braking Distance",
    q:"Which factor does NOT directly affect the braking distance of a vehicle?",
    opts:["Vehicle speed","Road surface friction","Engine displacement (cc)","Tyre condition"],
    ans:2,
    exp:"Braking distance depends on: Vehicle SPEED (most critical, distance is proportional to v squared), road surface friction coefficient, tyre condition, brake type, and vehicle load.\n\nEngine displacement (cc) has NO direct effect on braking distance at all. A 1000cc car can have better brakes than a 2000cc car. Engine size affects power and acceleration, not stopping distance.",
    tip:"Braking distance is proportional to v squared. Double the speed = 4x braking distance. Engine cc = power output = has NOTHING to do with stopping. This is a very common MPSC trap question.",
  },
  {
    id:3, level:"BASIC", topic:"ABS System",
    q:"The PRIMARY purpose of ABS (Anti-lock Braking System) is to:",
    opts:["Reduce braking distance on all road surfaces","Prevent wheel lock-up during hard braking to maintain steering control","Automatically apply brakes when obstacle is detected","Increase brake pad life by reducing brake force"],
    ans:1,
    exp:"ABS PRIMARY purpose: PREVENT WHEEL LOCK-UP during hard braking to maintain STEERING CONTROL.\n\nWhen wheels lock and skid: tyre slides instead of rolling = LESS friction = longer stopping distance AND driver loses the ability to steer.\n\nABS modulates brake pressure 10-15 times per second, keeping wheels just below lock-up. Wheels keep rolling = driver can still steer during emergency braking.\n\nNote: On loose gravel or sand, ABS may slightly increase stopping distance but steering is always maintained.",
    tip:"ABS = STEER while braking hard. Primary benefit = STEERING CONTROL, not necessarily shorter distance. Pedal pulsation during hard braking = ABS working NORMALLY. Do NOT pump the pedal with ABS, hold it firmly.",
  },
  {
    id:4, level:"MEDIUM", topic:"Pascal Law",
    q:"In a hydraulic brake system, master cylinder area = 5 cm2 and wheel cylinder area = 20 cm2. The force multiplication factor is:",
    opts:["2x","4x","5x","0.25x"],
    ans:1,
    exp:"Pascal Law: Pressure applied to enclosed fluid is transmitted equally in all directions.\n\nPressure = Force / Area. Since pressure is equal throughout:\n\nForce multiplication = Wheel cylinder area / Master cylinder area = 20 / 5 = 4x\n\nA 50N pedal force becomes 200N at the wheel cylinder (approximately, before losses). This is why hydraulic brakes are so effective with relatively light pedal pressure.",
    tip:"Force multiplication = Wheel cylinder area divided by Master cylinder area. Larger wheel cylinder = more force multiplication. Pascal Law is the working principle of ALL hydraulic brakes. Simple but frequently asked calculation.",
  },
  {
    id:5, level:"MEDIUM", topic:"Suspension",
    q:"MacPherson strut suspension is most commonly used on which axle and vehicle type?",
    opts:["Rear axle of luxury sedans","Front axle of small to medium passenger cars","Rear axle of trucks and buses","All four wheels of heavy SUVs"],
    ans:1,
    exp:"MacPherson Strut is used on FRONT axle of small to medium-sized passenger cars (both FWD and RWD vehicles).\n\nWhy front axle: The strut (combined spring + shock absorber) is compact, saves engine bay space, allows steering via top mount bearing, and is very cost-effective with fewer parts.\n\nExamples: Maruti Suzuki Swift, Hyundai i20, Honda City, VW Polo, almost all small-medium cars use MacPherson strut on front.",
    tip:"MacPherson = FRONT suspension of most passenger cars. 1 strut on top + 1 lower control arm = just 2 major parts. Simple, compact, lightweight. Named after Earle MacPherson (Ford engineer, 1945). Over 70% of modern passenger cars worldwide use this on front axle.",
  },
  {
    id:6, level:"MEDIUM", topic:"Drum vs Disc",
    q:"Which is a key DISADVANTAGE of drum brakes compared to disc brakes?",
    opts:["Drum brakes provide less initial braking force","Drum brakes are more expensive to manufacture","Drum brakes suffer from brake fade due to enclosed heat buildup","Drum brakes cannot work with ABS systems"],
    ans:2,
    exp:"KEY disadvantage of drum brakes: BRAKE FADE due to heat buildup.\n\nDrum is a CLOSED system, heat generated by friction is trapped inside the drum. As temperature rises, friction lining coefficient reduces, braking force drops. Brake fluid can vapourise (vapour lock) causing a spongy pedal.\n\nDisc brakes: Open design, rotor exposed to airflow, much better heat dissipation, no fade.\n\nDrum brakes CAN work with ABS. They ARE cheaper. They CAN generate HIGH initial force via self-energising action. Fade is their main weakness.",
    tip:"Drum = Enclosed = heat trapped = FADE. Disc = Open = heat dissipated = NO FADE. This is the most important drum vs disc difference. Ventilated disc (with internal air channels) dissipates heat even better than solid disc.",
  },
  {
    id:7, level:"MEDIUM", topic:"Wheel Alignment",
    q:"Which alignment angle describes the inward or outward tilt of the wheel when viewed from the FRONT of the vehicle?",
    opts:["Castor","Toe","Camber","King pin inclination"],
    ans:2,
    exp:"CAMBER: Angle of wheel from vertical, viewed from FRONT of vehicle.\n\nPositive camber = top of wheel tilts OUTWARD. Negative camber = top tilts INWARD (better for cornering). Zero = perfectly vertical.\n\nOther angles and their viewing directions:\nCASTOR = viewed from SIDE of vehicle (steering axis forward/backward tilt)\nTOE = viewed from TOP of vehicle (wheels pointing in or out)\nKPI = king pin axis tilt, viewed from FRONT",
    tip:"CAMBER = viewed from FRONT. CASTER = viewed from SIDE. TOE = viewed from TOP. Each angle has a different viewing direction, this is frequently tested! Excessive positive camber causes outer tyre edge wear. Excessive negative causes inner edge wear.",
  },
  {
    id:8, level:"HARD", topic:"ABS Components",
    q:"In an ABS system, which component detects individual wheel speed and sends signals to the ABS ECU?",
    opts:["Hydraulic control unit (HCU)","Wheel speed sensor","Brake pressure modulator","ABS pump motor"],
    ans:1,
    exp:"ABS has four key components:\n\n1. WHEEL SPEED SENSOR (WSS): Detects rotational speed of each individual wheel. Two types: passive inductive (older, generates AC voltage) and active Hall effect (modern, digital signal, accurate even at very slow speeds).\n\n2. ABS ECU: Receives speed signals from all 4 sensors. Detects rapid deceleration of any wheel (impending lock-up). Commands the HCU.\n\n3. HYDRAULIC CONTROL UNIT (HCU): Solenoid valves that reduce, hold, or increase brake pressure to individual wheels.\n\n4. ABS PUMP: Re-pressurizes brake fluid after pressure is released.",
    tip:"ABS sequence = Sense, Think, Act. Sense = Wheel speed sensor. Think = ECU. Act = HCU solenoid valves. Hall effect sensor is active and digital, accurate even at very slow speeds, and can detect wheel bearing wear. Used in all modern ABS systems.",
  },
  {
    id:9, level:"HARD", topic:"Shock Absorber",
    q:"A shock absorber (damper) dissipates energy by which mechanism?",
    opts:["Storing energy as potential energy in a spring","Converting kinetic energy to heat via hydraulic fluid resistance","Generating electricity via electromagnetic induction","Using compressed gas as a spring element"],
    ans:1,
    exp:"Shock absorber working principle:\n\nA piston moves through OIL inside a cylinder. Small orifices (restriction holes) in the piston restrict oil flow, creating resistance proportional to piston velocity. This resistance force opposes suspension movement and converts kinetic energy to HEAT in the oil.\n\nIMPORTANT DISTINCTION:\nSPRING = stores energy, supports vehicle weight, does NOT dissipate energy\nSHOCK ABSORBER = dissipates energy as heat, controls spring oscillation\nBoth work together as a spring-damper system for ride comfort and handling.",
    tip:"Spring STORES energy. Shock absorber DISSIPATES energy as heat. Without shock absorber, car bounces continuously. Without spring, car is rigid. They must work TOGETHER. Key concept: damper converts kinetic energy to heat via oil viscosity resistance.",
  },
  {
    id:10, level:"HARD", topic:"Braking Formula",
    q:"A vehicle at 60 km/h brakes on dry road (friction coefficient = 0.7). Using s = v2 / (2 x μ x g), what is the approximate braking distance?",
    opts:["10.2 metres","20.2 metres","40.4 metres","5.1 metres"],
    ans:1,
    exp:"Step 1: Convert speed to m/s: 60 km/h divided by 3.6 = 16.67 m/s\n\nStep 2: Apply formula:\ns = v2 / (2 x μ x g)\ns = (16.67)2 / (2 x 0.7 x 9.81)\ns = 277.9 / 13.734\ns = 20.2 metres\n\nAt 120 km/h (double speed):\ns = (33.33)2 / 13.734 = 1111 / 13.734 = 80.8 metres (4 times the distance)\n\nDouble speed always gives 4x braking distance (square law).",
    tip:"Formula: s = v2 / (2 x μ x g). Always convert km/h to m/s first by dividing by 3.6. Key result: double speed = 4x braking distance. This square relationship is frequently tested as a calculation in MPSC Mains.",
  },
  {
    id:11, level:"EXAM SPECIAL", topic:"Parking Brake",
    q:"The handbrake (parking brake) operates on REAR wheels via a mechanical cable. Why rear wheels and not front?",
    opts:["Rear brakes are always more powerful than front","Front wheels must remain free for steering; rear brakes are underused in service braking so parking brake supplements them","Hydraulic brakes cannot be used as parking brakes","ABS only covers front wheels"],
    ans:1,
    exp:"Parking brake on REAR wheels for these reasons:\n\n1. STEERING: Front wheels must be free to turn for steering. A mechanically locked front wheel could prevent parking on curves or cause loss of control.\n\n2. WEIGHT TRANSFER: During service braking, weight shifts FORWARD. Front brakes do 70% of work. Rear brakes are relatively underloaded in normal braking, so parking brake effectively uses this spare capacity.\n\n3. SIMPLE CABLE ROUTING: Easier to route a cable from cabin handbrake lever to rear axle.\n\n4. EMERGENCY USE: If hydraulic brakes fail, handbrake can slow vehicle using rear brakes only.",
    tip:"Parking brake = rear wheels = mechanical cable (or EPB electric motor). Why rear? Steering need at front + weight transfer leaves rear brakes underloaded in service braking. Modern EPB (Electronic Parking Brake) uses electric motor in rear caliper. Auto-releases when pulling away.",
  },
  {
    id:12, level:"EXAM SPECIAL", topic:"Suspension Types",
    q:"Which suspension uses a combined spring-damper strut at top with one lower control arm, and is the MOST COMMON front suspension on modern passenger cars?",
    opts:["Double wishbone suspension","Multi-link suspension","MacPherson strut suspension","Leaf spring suspension"],
    ans:2,
    exp:"MacPherson Strut suspension description:\nUPPER = strut (coil spring + shock absorber combined into one unit) connected to body via upper mount bearing that allows steering\nLOWER = single lower control arm (transverse link) that locates the wheel\n\nWhy most common on passenger cars:\n- Only 2 major components vs 4 or more for double wishbone\n- Compact design saves valuable engine bay space\n- Lower manufacturing and service cost\n- Works perfectly with FWD packaging\n- Used on over 70% of modern passenger cars worldwide on front axle",
    tip:"MacPherson = Strut on top + ONE lower control arm = 2 parts. Double wishbone = upper arm + lower arm + separate spring/damper = 4 or more parts. Multi-link = 3-5 separate links. More complexity = better geometry control = used on premium and performance cars rear suspension.",
  },
];

// ── SECTION COMPONENTS ──

function IntroSec() {
  return (
    <div>
      <STitle icon="🛑" title="INTRO — BRAKING AND SUSPENSION" sub="Safety-critical systems — exam relevance and ARTO job connection" color={C.red} />
      <Box glow={C.red} style={{ borderTop:"3px solid "+C.red, marginBottom:20 }}>
        <div style={{ fontFamily:"monospace", fontSize:11, color:C.red, letterSpacing:1.5, marginBottom:14 }}>WHY THESE TWO TOPICS TOGETHER?</div>
        <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:12 }}>
          {[
            { icon:"🛑", t:"8% Mains Weightage", d:"Braking and Suspension = 12-15 marks in Mains. Asked in 8 out of 10 previous years." },
            { icon:"💼", t:"ARTO Job Function", d:"Vehicle fitness inspection includes checking brakes (pad thickness, fade) and suspension (shock absorbers, linkages). This is your primary job." },
            { icon:"⚖️", t:"MV Act Connection", d:"Section 109 MV Act: vehicle must be in roadworthy condition. Defective brakes or suspension = unfit vehicle = refuse fitness certificate." },
          ].map(function(c,i) { return (
            <div key={i} style={{ padding:14, background:C.bg, borderRadius:10, textAlign:"center" }}>
              <div style={{ fontSize:28, marginBottom:8 }}>{c.icon}</div>
              <div style={{ color:C.red, fontWeight:700, fontSize:13, marginBottom:4 }}>{c.t}</div>
              <div style={{ color:C.soft, fontSize:12, lineHeight:1.6 }}>{c.d}</div>
            </div>
          ); })}
        </div>
      </Box>
      <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:16 }}>
        <Box style={{ borderTop:"2px solid "+C.red }}>
          <div style={{ fontFamily:"monospace", fontSize:11, color:C.red, letterSpacing:1, marginBottom:12 }}>BRAKING SYSTEM — OVERVIEW</div>
          <p style={{ color:C.text, fontSize:13, lineHeight:1.8 }}>The braking system converts the vehicle's kinetic energy into heat energy through friction. It is the single most critical safety system in any motor vehicle.</p>
          {[
            { t:"Primary (Service) Brake", d:"Main hydraulic brakes on all 4 wheels. Operated by brake pedal." },
            { t:"Secondary (Parking) Brake", d:"Mechanical cable to rear brakes. Handbrake or EPB." },
            { t:"Engine Brake", d:"Exhaust braking, compression release on trucks. Supplements service brakes." },
            { t:"Retarder", d:"Electromagnetic or hydrodynamic. Used on heavy commercial vehicles." },
          ].map(function(x,i) { return (
            <div key={i} style={{ padding:"8px 0", borderBottom:"1px solid "+C.border+"40" }}>
              <div style={{ color:C.yellow, fontSize:12, fontWeight:700 }}>{x.t}</div>
              <div style={{ color:C.soft, fontSize:12, marginTop:2 }}>{x.d}</div>
            </div>
          ); })}
        </Box>
        <Box style={{ borderTop:"2px solid "+C.blue }}>
          <div style={{ fontFamily:"monospace", fontSize:11, color:C.blue, letterSpacing:1, marginBottom:12 }}>SUSPENSION SYSTEM — OVERVIEW</div>
          <p style={{ color:C.text, fontSize:13, lineHeight:1.8 }}>The suspension system isolates the vehicle body from road irregularities, maintains tyre contact with road, and provides correct steering geometry for safe handling.</p>
          {[
            { t:"Spring", d:"Supports vehicle weight. Absorbs road shocks. Types: coil, leaf, torsion bar, air." },
            { t:"Shock Absorber (Damper)", d:"Controls spring oscillations. Converts kinetic energy to heat." },
            { t:"Linkages and Arms", d:"Wishbones, control arms — maintain wheel geometry during travel." },
            { t:"Anti-roll Bar", d:"Torsion bar linking left and right suspension — reduces body roll in corners." },
          ].map(function(x,i) { return (
            <div key={i} style={{ padding:"8px 0", borderBottom:"1px solid "+C.border+"40" }}>
              <div style={{ color:C.blue, fontSize:12, fontWeight:700 }}>{x.t}</div>
              <div style={{ color:C.soft, fontSize:12, marginTop:2 }}>{x.d}</div>
            </div>
          ); })}
        </Box>
      </div>
    </div>
  );
}

function DrumDiscSec() {
  var [active, setActive] = useState("drum");
  var drumParts = [
    { p:"Brake Drum", d:"Rotating cylindrical component bolted to wheel hub. Inner surface is the friction surface." },
    { p:"Brake Shoes", d:"Two curved shoes with friction lining on outer curved face. Pivot on anchor pin." },
    { p:"Wheel Cylinder", d:"Hydraulic actuator at top. Pistons push shoes outward when brake fluid pressure rises." },
    { p:"Return Springs", d:"Pull shoes back when brakes released. Maintain clearance between shoe and drum." },
    { p:"Anchor Pin", d:"Pivot point at bottom. One end of each shoe rests here." },
    { p:"Adjuster", d:"Maintains correct shoe-to-drum clearance as lining wears. Manual or automatic." },
  ];
  var discParts = [
    { p:"Disc Rotor", d:"Flat circular disc bolted to wheel hub. Rotates with wheel. Cast iron or carbon ceramic." },
    { p:"Brake Caliper", d:"Fixed or floating housing containing pistons. Straddles the disc from both sides." },
    { p:"Brake Pads", d:"Friction material mounted in caliper. Pressed against both sides of disc." },
    { p:"Caliper Piston(s)", d:"Hydraulic piston(s) that push pad against disc face. One or multiple per side." },
    { p:"Bleed Nipple", d:"Screw valve to remove air from hydraulic system during brake bleeding." },
    { p:"Wear Indicator", d:"Metal tab contacts disc when pad worn too thin — squealing sound = change pads." },
  ];
  return (
    <div>
      <STitle icon="🔴" title="DRUM vs DISC BRAKES" sub="Construction, working, comparison — most asked brake topic" color={C.red} />
      <div style={{ display:"flex", gap:10, marginBottom:20 }}>
        {[{id:"drum",l:"Drum Brake"},{id:"disc",l:"Disc Brake"}].map(function(t) { return (
          <button key={t.id} onClick={function(){ setActive(t.id); }} style={{
            flex:1, padding:"11px", borderRadius:10, border:"2px solid "+(active===t.id?C.red:C.border),
            background:active===t.id?C.red+"15":C.card, color:active===t.id?C.red:C.soft,
            fontFamily:"monospace", fontSize:12, cursor:"pointer", transition:"all 0.15s",
          }}>{t.l}</button>
        ); })}
      </div>

      {active==="drum" && (
        <div>
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:16, marginBottom:16 }}>
            <Box>
              <svg viewBox="0 0 260 200" style={{ width:"100%" }}>
                <rect width="260" height="200" fill="#090C10" rx="8"/>
                <text x="130" y="16" fill={C.text} fontSize="10" textAnchor="middle" fontFamily="monospace" fontWeight="bold">DRUM BRAKE — CROSS SECTION</text>
                <circle cx="130" cy="108" r="78" fill="none" stroke={C.muted} strokeWidth="14"/>
                <circle cx="130" cy="108" r="68" fill={C.bg} stroke={C.border} strokeWidth="1"/>
                <path d="M 72 55 Q 48 108 72 162" stroke={C.red} strokeWidth="7" fill="none" strokeLinecap="round"/>
                <path d="M 188 55 Q 212 108 188 162" stroke={C.red} strokeWidth="7" fill="none" strokeLinecap="round"/>
                <rect x="112" y="52" width="36" height="16" rx="3" fill={C.blue} fillOpacity="0.7"/>
                <text x="130" y="64" fill={C.text} fontSize="7" textAnchor="middle" fontFamily="monospace">WHEEL CYL</text>
                <circle cx="130" cy="162" r="5" fill={C.yellow}/>
                <text x="130" y="180" fill={C.yellow} fontSize="7" textAnchor="middle" fontFamily="monospace">ANCHOR PIN</text>
                <line x1="82" y1="108" x2="178" y2="108" stroke={C.green} strokeWidth="1.5" strokeDasharray="4,3"/>
                <text x="130" y="103" fill={C.green} fontSize="6" textAnchor="middle" fontFamily="monospace">RETURN SPRING</text>
                <circle cx="130" cy="108" r="16" fill={C.muted} fillOpacity="0.5"/>
                <circle cx="130" cy="108" r="7" fill={C.bg} stroke={C.soft} strokeWidth="1.5"/>
                <text x="42" y="108" fill={C.red} fontSize="7" textAnchor="middle" fontFamily="monospace">SHOE</text>
                <text x="218" y="108" fill={C.red} fontSize="7" textAnchor="middle" fontFamily="monospace">SHOE</text>
              </svg>
            </Box>
            <Box>
              <div style={{ fontFamily:"monospace", color:C.red, fontSize:11, letterSpacing:1, marginBottom:12 }}>DRUM BRAKE COMPONENTS</div>
              {drumParts.map(function(x,i) { return (
                <div key={i} style={{ padding:"7px 0", borderBottom:"1px solid "+C.border+"40" }}>
                  <div style={{ color:C.red, fontSize:12, fontWeight:700 }}>{x.p}</div>
                  <div style={{ color:C.soft, fontSize:12, marginTop:2 }}>{x.d}</div>
                </div>
              ); })}
            </Box>
          </div>
          <Box style={{ borderLeft:"3px solid "+C.red }}>
            <div style={{ fontFamily:"monospace", color:C.red, fontSize:11, letterSpacing:1, marginBottom:10 }}>SELF-ENERGISING ACTION — KEY EXAM CONCEPT</div>
            <p style={{ color:C.text, fontSize:13, lineHeight:1.8 }}>The LEADING SHOE (in direction of drum rotation) has friction force that rotates it further INTO the drum — amplifying braking force without extra pedal effort. This is called SELF-ENERGISATION. Leading shoe generates MORE braking force than the trailing shoe. Makes drum brakes very powerful with low pedal force — a unique advantage over disc brakes.</p>
          </Box>
        </div>
      )}

      {active==="disc" && (
        <div>
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:16, marginBottom:16 }}>
            <Box>
              <svg viewBox="0 0 260 200" style={{ width:"100%" }}>
                <rect width="260" height="200" fill="#090C10" rx="8"/>
                <text x="130" y="16" fill={C.text} fontSize="10" textAnchor="middle" fontFamily="monospace" fontWeight="bold">DISC BRAKE — CROSS SECTION</text>
                <circle cx="130" cy="108" r="72" fill="none" stroke={C.muted} strokeWidth="11"/>
                <circle cx="130" cy="108" r="58" fill={C.bg} stroke={C.border} strokeWidth="1"/>
                {[0,60,120,180,240,300].map(function(a,i) { return (
                  <line key={i}
                    x1={130+52*Math.cos(a*Math.PI/180)} y1={108+52*Math.sin(a*Math.PI/180)}
                    x2={130+66*Math.cos(a*Math.PI/180)} y2={108+66*Math.sin(a*Math.PI/180)}
                    stroke={C.border} strokeWidth="2.5"/>
                ); })}
                <rect x="52" y="82" width="52" height="52" rx="5" fill={C.blue} fillOpacity="0.2" stroke={C.blue} strokeWidth="1.5"/>
                <rect x="65" y="92" width="11" height="34" rx="3" fill={C.red} fillOpacity="0.8"/>
                <rect x="82" y="92" width="11" height="34" rx="3" fill={C.red} fillOpacity="0.8"/>
                <text x="78" y="152" fill={C.blue} fontSize="7" textAnchor="middle" fontFamily="monospace">CALIPER</text>
                <text x="74" y="88" fill={C.text} fontSize="6" fontFamily="monospace">PADS</text>
                <text x="186" y="88" fill={C.muted} fontSize="7" fontFamily="monospace">ROTOR/DISC</text>
                <circle cx="130" cy="108" r="19" fill={C.muted} fillOpacity="0.4"/>
                <circle cx="130" cy="108" r="8" fill={C.bg} stroke={C.soft} strokeWidth="1.5"/>
                <line x1="52" y1="108" x2="24" y2="108" stroke={C.yellow} strokeWidth="2"/>
                <text x="20" y="105" fill={C.yellow} fontSize="6" textAnchor="end" fontFamily="monospace">FLUID</text>
              </svg>
            </Box>
            <Box>
              <div style={{ fontFamily:"monospace", color:C.blue, fontSize:11, letterSpacing:1, marginBottom:12 }}>DISC BRAKE COMPONENTS</div>
              {discParts.map(function(x,i) { return (
                <div key={i} style={{ padding:"7px 0", borderBottom:"1px solid "+C.border+"40" }}>
                  <div style={{ color:C.blue, fontSize:12, fontWeight:700 }}>{x.p}</div>
                  <div style={{ color:C.soft, fontSize:12, marginTop:2 }}>{x.d}</div>
                </div>
              ); })}
            </Box>
          </div>
          <Box style={{ borderLeft:"3px solid "+C.blue, marginBottom:16 }}>
            <div style={{ fontFamily:"monospace", color:C.blue, fontSize:11, letterSpacing:1, marginBottom:10 }}>FLOATING vs FIXED CALIPER</div>
            <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:12 }}>
              <div style={{ padding:14, background:C.bg, borderRadius:8 }}>
                <div style={{ color:C.blue, fontWeight:700, marginBottom:8 }}>Floating (Sliding) Caliper</div>
                <div style={{ color:C.soft, fontSize:12, lineHeight:1.7 }}>ONE piston on inboard side. Hydraulic pressure pushes inboard pad AND reaction force slides caliper outward to press outboard pad. Simpler and cheaper. Used on most budget cars worldwide.</div>
              </div>
              <div style={{ padding:14, background:C.bg, borderRadius:8 }}>
                <div style={{ color:C.yellow, fontWeight:700, marginBottom:8 }}>Fixed (Opposed) Caliper</div>
                <div style={{ color:C.soft, fontSize:12, lineHeight:1.7 }}>Multiple pistons on BOTH sides of disc. Both pads press simultaneously. Better braking feel and less caliper flex. Used in performance and luxury cars (4-pot, 6-pot Brembo calipers).</div>
              </div>
            </div>
          </Box>
        </div>
      )}

      <Box style={{ marginTop:20, borderTop:"2px solid "+C.yellow }}>
        <div style={{ fontFamily:"monospace", color:C.yellow, fontSize:11, letterSpacing:1, marginBottom:12 }}>DRUM vs DISC — COMPLETE COMPARISON TABLE</div>
        <DataTable
          heads={["Parameter","Drum Brake","Disc Brake"]}
          rows={[
            ["Friction surface","Inner curved surface of drum","Flat faces of disc rotor"],
            ["Actuating element","Brake shoes push OUTWARD","Brake pads clamp from both sides"],
            ["Heat dissipation","POOR (enclosed drum)","EXCELLENT (open, ventilated)"],
            ["Brake fade resistance","LOW — fades under heavy use","HIGH — fade resistant"],
            ["Self-energising","YES — leading shoe amplifies force","NO — no self-energising"],
            ["Wet weather","POOR — water enters drum","GOOD — disc wiped clean by pads"],
            ["Cost","LOWER — cheaper to manufacture","HIGHER — complex caliper"],
            ["Parking brake","Easy — shoe acts as parking brake","Complex — needs separate mechanism"],
            ["Applications","Rear on budget cars, all commercial","Front all cars, rear on premium cars"],
          ]}
          hi={[2,3,5]}
        />
      </Box>
    </div>
  );
}

function HydraulicSec() {
  return (
    <div>
      <STitle icon="💧" title="HYDRAULIC BRAKE SYSTEM AND ABS" sub="Master cylinder, brake fluid, bleeding, ABS — complete circuit" color={C.blue} />
      <Box style={{ marginBottom:20 }}>
        <div style={{ fontFamily:"monospace", color:C.blue, fontSize:11, letterSpacing:1, marginBottom:12 }}>HYDRAULIC CIRCUIT — COMPONENTS IN ORDER</div>
        <div style={{ display:"grid", gap:10 }}>
          {[
            { c:"Brake Pedal and Booster", col:C.yellow, d:"Pedal provides mechanical input. Vacuum servo (brake booster) multiplies pedal force using engine intake manifold vacuum. Boost ratio: 3:1 to 4:1. EVs use electric vacuum pump." },
            { c:"Master Cylinder", col:C.blue, d:"Converts mechanical force to hydraulic pressure. Tandem master cylinder has TWO pistons in series — one for front circuit, one for rear. If one circuit fails, other still works for safety." },
            { c:"Brake Fluid Reservoir", col:C.teal, d:"Stores DOT brake fluid. Connected to master cylinder. Low fluid level = worn pads or a leak. Check regularly." },
            { c:"Proportioning Valve", col:C.orange, d:"Limits hydraulic pressure to REAR brakes relative to front during heavy braking. Prevents rear wheel lock-up as weight transfers forward during braking." },
            { c:"ABS Modulator / HCU", col:C.purple, d:"Hydraulic Control Unit with solenoid valves and pump. Modulates pressure to individual wheel calipers during ABS operation. Installed in brake line." },
            { c:"Brake Lines and Hoses", col:C.soft, d:"Steel hard lines (rigid) plus rubber flexible hoses at wheels (allow suspension movement). Spongy pedal = air in lines — bleed the system." },
            { c:"Wheel Cylinders or Calipers", col:C.red, d:"Convert hydraulic pressure back to mechanical force. Wheel cylinder (drum) has 2 pistons pushing shoes out. Caliper (disc) has 1-6 pistons pressing pads against rotor." },
          ].map(function(x,i) { return (
            <div key={i} style={{ display:"flex", gap:14, padding:"12px 14px", background:C.bg, borderRadius:8 }}>
              <div style={{ width:4, background:x.col, borderRadius:2, flexShrink:0 }} />
              <div>
                <div style={{ color:x.col, fontWeight:700, fontSize:13, marginBottom:4 }}>{x.c}</div>
                <div style={{ color:C.soft, fontSize:13, lineHeight:1.6 }}>{x.d}</div>
              </div>
            </div>
          ); })}
        </div>
      </Box>

      <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:16, marginBottom:20 }}>
        <Box style={{ borderTop:"2px solid "+C.blue }}>
          <div style={{ fontFamily:"monospace", color:C.blue, fontSize:11, letterSpacing:1, marginBottom:12 }}>BRAKE FLUID TYPES</div>
          <DataTable
            heads={["Type","Wet Boiling Pt","Note"]}
            rows={[
              ["DOT 3","140°C","Basic, hygroscopic, common"],
              ["DOT 4","155°C","Most common, standard use"],
              ["DOT 5","180°C","Silicone, NOT for ABS systems"],
              ["DOT 5.1","175°C","High performance, ABS compatible"],
            ]}
            hi={[1]}
          />
          <div style={{ marginTop:12, padding:"10px", background:C.blue+"10", borderRadius:8, fontSize:12, color:C.text }}>Hygroscopic = absorbs moisture from air. Water lowers boiling point, causes vapour lock and brake fade. Change DOT 3 and DOT 4 every 2 years.</div>
        </Box>
        <Box style={{ borderTop:"2px solid "+C.orange }}>
          <div style={{ fontFamily:"monospace", color:C.orange, fontSize:11, letterSpacing:1, marginBottom:12 }}>BRAKE BLEEDING ORDER</div>
          <p style={{ color:C.text, fontSize:13, lineHeight:1.7, marginBottom:10 }}>When air enters hydraulic brake lines, the air is compressible causing pedal to go soft or spongy. Air must be purged (bled) out.</p>
          <div style={{ fontWeight:700, color:C.yellow, fontSize:12, marginBottom:8 }}>Bleeding order (farthest from master cylinder first):</div>
          {["1. Right rear wheel (farthest from master cylinder)","2. Left rear wheel","3. Right front wheel","4. Left front wheel (nearest to master cylinder)"].map(function(s,i) { return (
            <div key={i} style={{ color:C.text, fontSize:12, padding:"5px 0", display:"flex", gap:8 }}>
              <span style={{ color:C.orange }}>→</span>{s}
            </div>
          ); })}
        </Box>
      </div>

      <Box style={{ borderTop:"2px solid "+C.purple }}>
        <div style={{ fontFamily:"monospace", color:C.purple, fontSize:11, letterSpacing:1, marginBottom:12 }}>ABS — ANTI-LOCK BRAKING SYSTEM — COMPLETE</div>
        <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:16 }}>
          <div>
            <div style={{ color:C.yellow, fontWeight:700, fontSize:13, marginBottom:10 }}>How ABS Works — Step by Step</div>
            {[
              "Driver brakes hard — hydraulic pressure rises to all 4 wheels",
              "Wheel speed sensors detect one wheel decelerating too fast (about to lock)",
              "ABS ECU identifies impending wheel lock-up",
              "ECU commands HCU solenoid valve to HOLD pressure to that wheel",
              "If wheel still decelerating: REDUCE pressure (dump to accumulator)",
              "Wheel recovers speed — pressure REAPPLIED by pump",
              "This cycle repeats 10-15 times per second",
              "Pedal vibrates / pulsates — this is ABS working NORMALLY",
              "Wheels keep rolling — driver maintains steering control",
            ].map(function(s,i) { return (
              <div key={i} style={{ display:"flex", gap:10, padding:"5px 0", borderBottom:"1px solid "+C.border+"30" }}>
                <span style={{ color:C.purple, fontFamily:"monospace", fontSize:10, flexShrink:0, minWidth:20 }}>{"0"+(i+1)}</span>
                <span style={{ color:C.text, fontSize:12, lineHeight:1.5 }}>{s}</span>
              </div>
            ); })}
          </div>
          <div>
            <div style={{ color:C.yellow, fontWeight:700, fontSize:13, marginBottom:10 }}>ABS Add-on Systems</div>
            {[
              { t:"EBD — Electronic Brake Distribution", d:"Auto-adjusts brake force front/rear based on load. Modern replacement of mechanical proportioning valve." },
              { t:"BA — Brake Assist", d:"Detects panic braking (sudden fast pedal press). Applies MAXIMUM brake force automatically even if driver does not press fully." },
              { t:"ESC or ESP", d:"Electronic Stability Control. Uses ABS hardware plus brakes individual wheels to prevent skid, oversteer, or understeer." },
              { t:"Hill Start Assist (HSA)", d:"Holds brake pressure for 2-3 seconds on hill start while driver moves foot to accelerator. Prevents rollback." },
              { t:"Hill Descent Control (HDC)", d:"Automatically modulates ABS to maintain slow controlled speed descending steep slopes. Off-road vehicles." },
            ].map(function(x,i) { return (
              <div key={i} style={{ padding:"8px 10px", background:C.bg, borderRadius:8, marginBottom:8, borderLeft:"2px solid "+C.purple+"60" }}>
                <div style={{ color:C.purple, fontWeight:700, fontSize:12 }}>{x.t}</div>
                <div style={{ color:C.soft, fontSize:12, marginTop:4, lineHeight:1.5 }}>{x.d}</div>
              </div>
            ); })}
          </div>
        </div>
      </Box>
    </div>
  );
}

function SuspensionSec() {
  var [at, setAt] = useState(0);
  var types = [
    {
      name:"MacPherson Strut", color:C.blue, tag:"MOST COMMON FRONT",
      desc:"Single combined coil spring and shock absorber (strut) as upper element, plus one lower control arm. Most used front suspension in passenger cars worldwide.",
      pros:["Simple — fewer parts","Compact — saves engine bay space","Low cost to manufacture","Works with FWD and RWD","Allows steering via top mount"],
      cons:["Camber changes with suspension travel","Not ideal for extreme performance","Limited geometry tuning"],
      use:"Maruti Swift/Baleno, Hyundai i20/Creta, Honda City, VW Polo — virtually all small-medium car front suspension",
      parts:["Strut (spring + damper combined)","Lower control arm","Anti-roll bar link","Upper strut mount bearing","Lower ball joint"],
    },
    {
      name:"Double Wishbone", color:C.green, tag:"PERFORMANCE AND LUXURY",
      desc:"Two wishbone-shaped control arms (upper and lower) with separate coil spring and shock absorber. Provides best geometry control of all suspension types.",
      pros:["Excellent camber control in corners","Superior handling","Independent spring and damper positioning","High tuning flexibility for engineers"],
      cons:["More complex — more parts","Higher manufacturing cost","Takes more space in engine bay"],
      use:"Honda City rear, Mahindra XUV700 front, sports cars, luxury SUVs, all racing cars",
      parts:["Upper wishbone (A-arm)","Lower wishbone (A-arm)","Coil spring (separate from damper)","Shock absorber (separate)","Upper and lower ball joints"],
    },
    {
      name:"Multi-Link", color:C.purple, tag:"BEST GEOMETRY",
      desc:"Three to five individual links per wheel, each controlling specific degrees of freedom. Most sophisticated suspension available. Independent tuning of all parameters.",
      pros:["Best wheel geometry control","Excellent ride and handling balance","Independent tuning of toe, camber, compliance"],
      cons:["Most complex of all types","Highest manufacturing cost","Difficult to service","Heavier than others"],
      use:"BMW 3-series rear, Mercedes C-class, Hyundai Tucson rear, all premium sedans and SUVs",
      parts:["3-5 individual lateral and longitudinal links","Knuckle","Coil spring","Shock absorber","Toe link (controls toe independently)"],
    },
    {
      name:"Leaf Spring", color:C.yellow, tag:"COMMERCIAL VEHICLES",
      desc:"Multiple steel strips (leaves) of progressively decreasing length stacked and clamped together. Simple, robust, very high load capacity. Universal in commercial vehicles.",
      pros:["Very high load capacity","Simple, robust, and cheap","Acts as its own locating member","Easy to inspect and repair"],
      cons:["Harsh ride quality (very stiff)","Poor handling in performance use","Heavy weight"],
      use:"ALL trucks, buses, and most commercial vehicles. Mahindra Bolero/Scorpio rear, all Tata trucks",
      parts:["Master leaf (longest, with eyes for mounting)","Graduated leaves (shorter)","Centre bolt","U-bolts (clamp to axle)","Shackle (allows length change on compression)"],
    },
    {
      name:"Torsion Bar", color:C.orange, tag:"TRUCKS AND SOME SUVS",
      desc:"A steel rod that resists twisting (torsion) acts as the spring element. When wheel hits bump, arm rotates, twisting the bar which resists. Adjustable ride height.",
      pros:["Compact — no coil spring needed","Adjustable ride height by rotating bar end","Durable and long lasting"],
      cons:["Adjustment range is limited","Less progressive spring rate than coil"],
      use:"Mahindra Scorpio and Thar front suspension, some Jeep models, older commercial trucks",
      parts:["Torsion bar (long steel rod)","Lower control arm","Adjusting bolt (ride height adjuster)","Anchor bracket at body"],
    },
    {
      name:"Air Suspension", color:C.teal, tag:"LUXURY AND HEAVY BUSES",
      desc:"Air springs (rubber bellows/air bags) replace conventional coil springs. Air pressure adjusted by compressor to change ride height and spring stiffness.",
      pros:["Adjustable ride height (driver selectable)","Variable stiffness — comfort or sport mode","Self-levelling under changing load","Smoothest ride of any suspension type"],
      cons:["Very expensive to buy and repair","Complex system — compressor, valves, ECU, sensors","Air leaks cause complete system failure"],
      use:"Mercedes S-class, BMW 7-series, Volvo/Scania trucks rear axle, all heavy luxury buses",
      parts:["Air spring bellows (rubber bag)","Air compressor","Solenoid valves","Ride height sensors","Suspension ECU","Air reservoir tank"],
    },
  ];
  var st = types[at];
  return (
    <div>
      <STitle icon="🔩" title="SUSPENSION SYSTEMS" sub="All six types — construction, working, pros, cons, applications" color={C.blue} />
      <div style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:8, marginBottom:20 }}>
        {types.map(function(s,i) { return (
          <button key={i} onClick={function(){ setAt(i); }} style={{
            padding:"10px 12px", borderRadius:10, textAlign:"left",
            border:"2px solid "+(at===i?s.color:C.border),
            background:at===i?s.color+"12":C.card, cursor:"pointer", transition:"all 0.15s",
          }}>
            <div style={{ fontFamily:"monospace", fontSize:10, color:at===i?s.color:C.muted, fontWeight:700, marginBottom:4 }}>{s.name}</div>
            <Tag label={s.tag} color={s.color} />
          </button>
        ); })}
      </div>
      <Box key={at} glow={st.color} style={{ borderTop:"3px solid "+st.color, marginBottom:20 }}>
        <div style={{ fontSize:20, color:st.color, fontWeight:700, letterSpacing:2, marginBottom:6 }}>{st.name}</div>
        <p style={{ color:C.text, fontSize:14, lineHeight:1.8, marginBottom:16 }}>{st.desc}</p>
        <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:14 }}>
          <div>
            <div style={{ fontFamily:"monospace", color:st.color, fontSize:10, letterSpacing:1, marginBottom:10 }}>KEY COMPONENTS</div>
            {st.parts.map(function(p,i) { return (
              <div key={i} style={{ color:C.text, fontSize:12, padding:"5px 0", borderBottom:"1px solid "+C.border+"40", display:"flex", gap:8 }}>
                <span style={{ color:st.color, flexShrink:0 }}>→</span>{p}
              </div>
            ); })}
          </div>
          <div>
            <div style={{ fontFamily:"monospace", color:C.green, fontSize:10, letterSpacing:1, marginBottom:10 }}>ADVANTAGES</div>
            {st.pros.map(function(p,i) { return (
              <div key={i} style={{ color:C.text, fontSize:12, padding:"4px 0", display:"flex", gap:8 }}>
                <span style={{ color:C.green }}>✓</span>{p}
              </div>
            ); })}
            <div style={{ fontFamily:"monospace", color:C.red, fontSize:10, letterSpacing:1, margin:"12px 0 8px" }}>LIMITATIONS</div>
            {st.cons.map(function(p,i) { return (
              <div key={i} style={{ color:C.text, fontSize:12, padding:"4px 0", display:"flex", gap:8 }}>
                <span style={{ color:C.red }}>✗</span>{p}
              </div>
            ); })}
          </div>
          <div>
            <div style={{ fontFamily:"monospace", color:C.yellow, fontSize:10, letterSpacing:1, marginBottom:10 }}>USED IN</div>
            <div style={{ padding:"12px", background:C.bg, borderRadius:8, color:C.soft, fontSize:12, lineHeight:1.7 }}>{st.use}</div>
          </div>
        </div>
      </Box>
      <Box style={{ borderTop:"2px solid "+C.yellow }}>
        <div style={{ fontFamily:"monospace", color:C.yellow, fontSize:11, letterSpacing:1, marginBottom:12 }}>SUSPENSION COMPARISON — QUICK REFERENCE</div>
        <DataTable
          heads={["Type","Load Capacity","Ride Quality","Handling","Cost","Best For"]}
          cols={[C.soft,C.blue,C.green,C.yellow,C.orange,C.teal]}
          rows={[
            ["MacPherson Strut","Medium","Good","Good","Low","Front — passenger cars"],
            ["Double Wishbone","Medium","Excellent","Excellent","High","Performance, luxury"],
            ["Multi-Link","Medium","Best","Best","Highest","Luxury rear, premium"],
            ["Leaf Spring","VERY HIGH","Harsh","Poor","Very Low","Commercial vehicles"],
            ["Torsion Bar","Medium-High","Good","Good","Medium","Trucks, some SUVs"],
            ["Air Suspension","Very High","Best","Variable","Very High","Luxury cars, heavy buses"],
          ]}
          hi={[0,3]}
        />
      </Box>
    </div>
  );
}

function AlignmentSec() {
  var [aa, setAa] = useState(0);
  var angles = [
    {
      name:"CAMBER", view:"View from FRONT", color:C.red,
      def:"Angle of wheel from true vertical, viewed from front of vehicle. Positive = top tilts out. Negative = top tilts in.",
      effect:"Affects tyre wear and cornering grip. Excessive positive camber causes outer tyre edge wear. Negative camber improves cornering grip.",
      types:["Positive camber — top of wheel tilts OUTWARD. Old cars, agricultural vehicles.","Negative camber — top tilts INWARD. Performance cars for better cornering.","Zero camber — wheel perfectly vertical. Good for straight-line stability."],
      value:"Typically: 0 to -2 degrees for passenger cars",
    },
    {
      name:"CASTOR", view:"View from SIDE", color:C.blue,
      def:"Angle of steering axis (king pin) from vertical, viewed from side of vehicle. Positive = top tilts backward toward driver.",
      effect:"Positive castor provides self-centring of steering like a shopping cart castor wheel. Higher positive castor = better straight-line stability but heavier steering.",
      types:["Positive castor — steering axis top tilts BACKWARD. Standard on ALL modern cars.","Negative castor — top tilts FORWARD. Causes instability. Not used in modern vehicles.","Zero castor — vertical steering axis. No self-centring tendency."],
      value:"Typically: +3 to +7 degrees positive castor",
    },
    {
      name:"TOE", view:"View from TOP", color:C.green,
      def:"Whether wheels point inward (toe-in) or outward (toe-out) when viewed from above the vehicle.",
      effect:"Toe-in causes outer tyre edge wear. Toe-out causes inner edge wear. Incorrect toe is the number one cause of abnormal front tyre wear.",
      types:["Toe-in (positive toe) — front of wheels are closer together. Standard for RWD vehicles.","Toe-out (negative toe) — front of wheels are farther apart. Used on FWD front axle.","Zero toe — wheels perfectly parallel to each other and to vehicle centreline."],
      value:"Typically: 0 to +3mm toe-in for RWD, slight toe-out for FWD",
    },
    {
      name:"KING PIN INCLINATION", view:"View from FRONT", color:C.yellow,
      def:"Angle of the king pin (steering pivot axis) from vertical, viewed from front of vehicle. Always positive (inward tilt at top).",
      effect:"Reduces steering effort. Provides self-centring tendency. Creates negative or zero scrub radius when combined with wheel offset for safety.",
      types:["KPI angle — always positive, top tilts INWARD. Typically 8 to 15 degrees."],
      value:"Typically: 8 to 15 degrees",
    },
    {
      name:"SCRUB RADIUS", view:"Measured at ground", color:C.orange,
      def:"Horizontal distance between where the steering axis meets the ground and the centre of the tyre contact patch.",
      effect:"Negative scrub radius — on unequal braking vehicle self-corrects toward better-grip side (safer). Positive — pulls toward harder-braking side (dangerous). Modern ABS cars use negative or zero.",
      types:["Positive scrub radius — axis meets ground INSIDE tyre centre. Older vehicles.","Negative scrub radius — axis meets ground OUTSIDE tyre centre. Modern safe design.","Zero scrub radius — axis meets exactly at tyre centre."],
      value:"Modern cars: negative or near-zero for ABS compatibility",
    },
  ];
  var a = angles[aa];
  return (
    <div>
      <STitle icon="📐" title="WHEEL ALIGNMENT GEOMETRY" sub="Camber, Castor, Toe, KPI, Scrub Radius — all five angles explained" color={C.yellow} />
      <Box style={{ marginBottom:20, borderLeft:"3px solid "+C.yellow, background:C.yellow+"08" }}>
        <div style={{ color:C.yellow, fontFamily:"monospace", fontSize:11, letterSpacing:1, marginBottom:8 }}>WHY WHEEL ALIGNMENT MATTERS FOR ARTO</div>
        <div style={{ color:C.text, fontSize:13, lineHeight:1.8 }}>During vehicle fitness inspection, improper wheel alignment is grounds for refusing fitness certificate. Signs include uneven tyre wear (outer or inner edge worn), vehicle pulling to one side, and steering not self-centring. All these affect road safety and must be identified.</div>
      </Box>
      <div style={{ display:"grid", gridTemplateColumns:"repeat(5,1fr)", gap:8, marginBottom:20 }}>
        {angles.map(function(an,i) { return (
          <button key={i} onClick={function(){ setAa(i); }} style={{
            padding:"10px 8px", borderRadius:10, border:"2px solid "+(aa===i?an.color:C.border),
            background:aa===i?an.color+"12":C.card, cursor:"pointer", transition:"all 0.15s", textAlign:"center",
          }}>
            <div style={{ fontFamily:"monospace", fontSize:9, color:aa===i?an.color:C.muted, fontWeight:700 }}>{an.name}</div>
            <div style={{ color:C.muted, fontSize:9, marginTop:4 }}>{an.view}</div>
          </button>
        ); })}
      </div>
      <Box key={aa} style={{ borderTop:"3px solid "+a.color, marginBottom:20 }}>
        <div style={{ display:"flex", gap:12, alignItems:"center", marginBottom:14 }}>
          <div style={{ fontSize:22, color:a.color, fontWeight:700, letterSpacing:3 }}>{a.name}</div>
          <Tag label={a.view} color={a.color} />
        </div>
        <p style={{ color:C.text, fontSize:14, lineHeight:1.8, marginBottom:14 }}>{a.def}</p>
        <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:14 }}>
          <div>
            <div style={{ fontFamily:"monospace", color:a.color, fontSize:10, letterSpacing:1, marginBottom:10 }}>TYPES</div>
            {a.types.map(function(t,i) { return (
              <div key={i} style={{ padding:"8px 12px", background:C.bg, borderRadius:8, marginBottom:8, borderLeft:"2px solid "+a.color+"60" }}>
                <div style={{ color:a.color, fontSize:12, lineHeight:1.6 }}>{t}</div>
              </div>
            ); })}
            <div style={{ padding:"8px 12px", background:C.yellow+"10", borderRadius:8, marginTop:10 }}>
              <span style={{ color:C.yellow, fontFamily:"monospace", fontSize:10 }}>TYPICAL VALUE: </span>
              <span style={{ color:C.text, fontSize:12 }}>{a.value}</span>
            </div>
          </div>
          <div style={{ padding:16, background:C.bg, borderRadius:10, borderLeft:"2px solid "+a.color+"40" }}>
            <div style={{ fontFamily:"monospace", color:a.color, fontSize:10, letterSpacing:1, marginBottom:10 }}>EFFECT ON VEHICLE</div>
            <div style={{ color:C.text, fontSize:13, lineHeight:1.8 }}>{a.effect}</div>
          </div>
        </div>
      </Box>
      <Box style={{ borderTop:"2px solid "+C.blue }}>
        <div style={{ fontFamily:"monospace", color:C.blue, fontSize:11, letterSpacing:1, marginBottom:12 }}>TYRE WEAR PATTERNS — ARTO INSPECTION DIAGNOSIS GUIDE</div>
        <DataTable
          heads={["Wear Pattern","Cause","Action"]}
          rows={[
            ["Centre tread worn (both edges ok)","Over-inflation — tyre bulges in middle","Reduce tyre pressure to specification"],
            ["Both edges worn (centre ok)","Under-inflation — tyre flattens on road","Increase tyre pressure to specification"],
            ["One outer edge worn","Excessive positive camber on that wheel","Adjust camber in wheel alignment"],
            ["One inner edge worn","Excessive negative camber on that wheel","Adjust camber in wheel alignment"],
            ["Feathered or scalloped edge","Incorrect toe setting","Adjust toe-in or toe-out"],
            ["Cupping or patchy wear","Worn shock absorbers — tyre bounces","Replace shock absorbers"],
            ["One-sided wear with pulling","Unequal camber or castor side to side","Full 4-wheel alignment check needed"],
          ]}
          hi={[5]}
        />
      </Box>
    </div>
  );
}

function ShockSec() {
  return (
    <div>
      <STitle icon="🌊" title="SHOCK ABSORBERS AND SPRINGS" sub="Working, types, testing and replacement — ARTO inspection guide" color={C.teal} />
      <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:16, marginBottom:20 }}>
        <Box style={{ borderTop:"2px solid "+C.teal }}>
          <div style={{ fontFamily:"monospace", color:C.teal, fontSize:11, letterSpacing:1, marginBottom:12 }}>HYDRAULIC SHOCK ABSORBER — HOW IT WORKS</div>
          <p style={{ color:C.text, fontSize:13, lineHeight:1.8, marginBottom:12 }}>A telescopic shock absorber has a piston moving through oil inside a sealed cylinder. Small orifices (restriction holes) in the piston restrict oil flow, creating a resistance force proportional to piston velocity. This converts kinetic energy to heat.</p>
          {[
            { s:"COMPRESSION STROKE (wheel hits bump)", c:C.orange, d:"Wheel moves up. Piston moves DOWN. Oil forced through compression valves. Compression damping resists the wheel moving upward too fast." },
            { s:"REBOUND STROKE (wheel drops)", c:C.blue, d:"Wheel moves down after bump. Piston moves UP. Oil forced through rebound valves. Rebound damping prevents wheel snapping down hard." },
          ].map(function(x,i) { return (
            <div key={i} style={{ padding:"10px 12px", background:C.bg, borderRadius:8, marginBottom:8, borderLeft:"2px solid "+x.c }}>
              <div style={{ color:x.c, fontWeight:700, fontSize:12, marginBottom:4 }}>{x.s}</div>
              <div style={{ color:C.soft, fontSize:12, lineHeight:1.6 }}>{x.d}</div>
            </div>
          ); })}
          <div style={{ marginTop:12, padding:"10px 12px", background:C.teal+"10", borderRadius:8 }}>
            <div style={{ color:C.teal, fontWeight:700, fontSize:12, marginBottom:4 }}>Gas-charged Shock Absorber</div>
            <div style={{ color:C.soft, fontSize:12 }}>Nitrogen gas at 10-20 bar in a separate chamber prevents oil foaming and cavitation under hard repeated use. Better fade resistance. Slightly firmer ride. Standard on performance and heavy vehicles.</div>
          </div>
        </Box>
        <Box style={{ borderTop:"2px solid "+C.yellow }}>
          <div style={{ fontFamily:"monospace", color:C.yellow, fontSize:11, letterSpacing:1, marginBottom:12 }}>SPRING TYPES</div>
          {[
            { t:"Coil Spring", c:C.blue, d:"Helical wound spring. Most common in independent suspension. Progressive rate possible with variable pitch winding." },
            { t:"Leaf Spring", c:C.yellow, d:"Multiple steel strips. Very high load capacity. Also serves as locating member for axle. Universal in commercial vehicles." },
            { t:"Torsion Bar", c:C.orange, d:"Steel rod twisted by suspension arm. Compact. Adjustable ride height. Used in Mahindra Scorpio and Thar front suspension." },
            { t:"Air Spring (Bellows)", c:C.purple, d:"Rubber bag filled with compressed air. Variable spring rate by changing air pressure. Used in luxury cars and heavy buses." },
            { t:"Rubber Buffer", c:C.teal, d:"Progressive bump stop at limit of travel. Prevents metal-to-metal contact at full compression. Always present as secondary spring." },
          ].map(function(x,i) { return (
            <div key={i} style={{ padding:"8px 0", borderBottom:"1px solid "+C.border+"40", display:"flex", gap:12 }}>
              <div style={{ width:3, background:x.c, borderRadius:2, flexShrink:0 }} />
              <div>
                <div style={{ color:x.c, fontWeight:700, fontSize:12 }}>{x.t}</div>
                <div style={{ color:C.soft, fontSize:12, marginTop:2, lineHeight:1.5 }}>{x.d}</div>
              </div>
            </div>
          ); })}
        </Box>
      </div>
      <Box style={{ borderTop:"2px solid "+C.red }}>
        <div style={{ fontFamily:"monospace", color:C.red, fontSize:11, letterSpacing:1, marginBottom:12 }}>SHOCK ABSORBER INSPECTION — ARTO FITNESS TEST GUIDE</div>
        <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:14 }}>
          <div>
            <div style={{ color:C.yellow, fontWeight:700, fontSize:13, marginBottom:10 }}>Symptoms of Worn Shock Absorbers</div>
            {[
              "Excessive bouncing after bump (more than 1-2 oscillations)",
              "Cupped or scalloped tyre wear pattern",
              "Vehicle nose-dives sharply under braking",
              "Excessive body roll in corners",
              "Steering feels vague or wandering at highway speed",
              "Visible oil leak on shock absorber body",
              "Knocking noise over bumps (worn rubber bushes)",
              "Vehicle sits lower on one corner (sagging spring)",
            ].map(function(s,i) { return (
              <div key={i} style={{ display:"flex", gap:8, padding:"6px 0", borderBottom:"1px solid "+C.border+"30", fontSize:12, color:C.text }}>
                <span style={{ color:C.red, flexShrink:0 }}>⚠</span>{s}
              </div>
            ); })}
          </div>
          <div>
            <div style={{ color:C.green, fontWeight:700, fontSize:13, marginBottom:10 }}>ARTO Bounce Test Procedure</div>
            <div style={{ padding:14, background:C.bg, borderRadius:10, marginBottom:12 }}>
              <div style={{ color:C.text, fontSize:13, lineHeight:2.0 }}>
                <strong style={{ color:C.green }}>Bounce Test Method:</strong><br/>
                1. Push down firmly on each corner of vehicle<br/>
                2. Release suddenly and step back<br/>
                3. Count the number of oscillations:<br/>
                <span style={{ color:C.green }}>→ 1 oscillation then stops = PASS</span><br/>
                <span style={{ color:C.red }}>→ 2 or more oscillations = FAIL fitness certificate</span><br/>
                4. Check for oil leak on shock body<br/>
                5. Check rubber bushes and mounting bolts<br/>
                6. Check for noise during bounce test
              </div>
            </div>
            <div style={{ padding:"10px 12px", background:C.green+"10", borderRadius:8 }}>
              <div style={{ color:C.green, fontWeight:700, fontSize:12, marginBottom:4 }}>Replacement Interval</div>
              <div style={{ color:C.soft, fontSize:12, lineHeight:1.6 }}>Generally every 50,000 to 80,000 km or every 4-6 years. Heavy use (trucks, buses, poor roads) requires earlier replacement. Always replace both sides of same axle together — never just one side.</div>
            </div>
          </div>
        </div>
      </Box>
    </div>
  );
}

function FormulasSec() {
  var [show, setShow] = useState([false,false,false,false]);
  function toggle(i) {
    var ns = show.slice();
    ns[i] = !ns[i];
    setShow(ns);
  }
  var formulas = [
    {
      name:"Braking Distance", formula:"s = v² / (2 × μ × g)", color:C.red,
      vars:[{s:"s",d:"Braking distance in metres"},{s:"v",d:"Initial speed in m/s (divide km/h by 3.6)"},{s:"μ",d:"Tyre-road friction coefficient (0.3 wet to 0.8 dry)"},{s:"g",d:"Gravity = 9.81 m/s²"}],
      example:"Vehicle at 60 km/h = 16.67 m/s. μ = 0.7, g = 9.81\ns = (16.67)² / (2 × 0.7 × 9.81) = 277.9 / 13.734 = 20.2 metres\n\nAt 120 km/h (double speed):\ns = (33.33)² / 13.734 = 1111 / 13.734 = 80.9 metres (4x distance!)\n\nKey Rule: Double speed = 4x braking distance (square law).",
    },
    {
      name:"Total Stopping Distance", formula:"Total = (v × t) + v² / (2 × μ × g)", color:C.orange,
      vars:[{s:"t",d:"Reaction time in seconds (average human = 0.75 to 1.5 seconds)"},{s:"v",d:"Speed in m/s"}],
      example:"Speed = 80 km/h = 22.2 m/s. Reaction time = 1 second. μ = 0.7\nReaction distance = 22.2 × 1 = 22.2 metres\nBraking distance = (22.2)² / (2 × 0.7 × 9.81) = 35.9 metres\nTotal stopping distance = 22.2 + 35.9 = 58.1 metres\n\nAlcohol doubles reaction time — doubles reaction distance — very dangerous!",
    },
    {
      name:"Hydraulic Force Multiplication", formula:"F_out / F_in = A_out / A_in", color:C.blue,
      vars:[{s:"F",d:"Force in Newtons"},{s:"A",d:"Cross-sectional area in cm² (Pascal Law applies)"}],
      example:"Master cylinder area = 5 cm². Wheel cylinder area = 20 cm².\nForce multiplication = 20 / 5 = 4x\nPedal force 100N → Wheel cylinder = 400N\nWith brake booster (4:1): Foot force 25N → Master 100N → Wheel 400N",
    },
    {
      name:"Maximum Deceleration Rate", formula:"a_max = μ × g  (m/s²)", color:C.purple,
      vars:[{s:"a",d:"Maximum deceleration in m/s² (also expressed as multiple of g)"},{s:"μ",d:"Tyre-road friction coefficient"},{s:"g",d:"9.81 m/s²"}],
      example:"Dry tarmac μ = 0.8: a_max = 0.8 × 9.81 = 7.85 m/s² (0.8g)\nWet road μ = 0.5: a_max = 0.5 × 9.81 = 4.9 m/s² (0.5g)\nIce μ = 0.15: a_max = 0.15 × 9.81 = 1.47 m/s² (only 0.15g!)\n\nThis is why stopping distances increase so dramatically on wet and icy roads.",
    },
  ];
  return (
    <div>
      <STitle icon="🔢" title="FORMULA AND CALCULATION SHEET" sub="Braking formulas for MPSC Mains — click for worked examples" color={C.yellow} />
      <div style={{ display:"grid", gap:14 }}>
        {formulas.map(function(f,i) { return (
          <Box key={i} style={{ borderLeft:"3px solid "+f.color, padding:16 }}>
            <div style={{ color:f.color, fontFamily:"monospace", fontSize:12, fontWeight:700, marginBottom:8 }}>{f.name}</div>
            <div style={{ background:C.bg, borderRadius:8, padding:"10px 16px", fontFamily:"monospace", fontSize:14, color:f.color, textAlign:"center", fontWeight:700, marginBottom:10 }}>{f.formula}</div>
            {f.vars.map(function(v,j) { return (
              <div key={j} style={{ display:"flex", gap:10, padding:"4px 0", borderBottom:"1px solid "+C.border+"40" }}>
                <span style={{ color:f.color, fontFamily:"monospace", fontSize:12, minWidth:90, flexShrink:0 }}>{v.s}</span>
                <span style={{ color:C.soft, fontSize:12 }}>{v.d}</span>
              </div>
            ); })}
            <button onClick={function(){ toggle(i); }} style={{ marginTop:10, background:"none", border:"1px solid "+f.color+"40", color:f.color, padding:"5px 14px", borderRadius:6, cursor:"pointer", fontSize:11, fontFamily:"monospace" }}>
              {show[i]?"▲ Hide":"▼ Worked Example"}
            </button>
            {show[i] && (
              <div style={{ background:f.color+"0C", borderRadius:8, padding:"12px 14px", marginTop:10, fontSize:12, color:C.text, fontFamily:"monospace", lineHeight:1.9, whiteSpace:"pre-line" }}>{f.example}</div>
            )}
          </Box>
        ); })}
      </div>
    </div>
  );
}

function TricksSec() {
  var tricks = [
    {
      icon:"🛑", title:"Drum vs Disc — One-Line Summary", color:C.red,
      items:[
        "DRUM: Enclosed drum = heat trapped = FADES. Advantage: self-energising, cheap, easy parking brake.",
        "DISC: Open rotor = heat dissipated = NO FADE. Advantage: better in rain (self-cleaning), high speed.",
        "All modern cars: DISC front always. Heavy trucks: DRUM all round (large drum has massive heat capacity).",
        "Brake fade = temporary loss of braking power due to heat. Most likely in drums during long hill descents.",
        "Vapour lock = brake fluid boils = air bubble in line = pedal goes to floor. Very dangerous. Change fluid every 2 years.",
        "ARTO inspection: Disc minimum pad thickness 2-3mm. Drum shoe lining minimum 1mm above rivet heads.",
      ],
    },
    {
      icon:"📐", title:"Alignment Angles — View Direction Memory Trick", color:C.yellow,
      items:[
        "CAMBER = viewed from FRONT — tilt of wheel left or right (positive outward, negative inward)",
        "CASTER = viewed from SIDE — forward or backward tilt of steering axis",
        "TOE = viewed from TOP — wheels pointing inward (toe-in) or outward (toe-out)",
        "KPI = viewed from FRONT — measures STEERING AXIS tilt, not wheel tilt",
        "CRITICAL: each angle has a DIFFERENT viewing direction — frequently tested in MPSC exams",
        "Tyre wear diagnosis: Edge worn = pressure wrong. One-edge worn = camber wrong. Feathered = toe wrong. Cupping = shock absorber worn.",
      ],
    },
    {
      icon:"🤖", title:"ABS — Key Facts for Exam", color:C.purple,
      items:[
        "ABS primary function = PREVENT WHEEL LOCK-UP = maintain STEERING CONTROL (not necessarily shorter distance).",
        "On loose gravel or sand: ABS may actually INCREASE stopping distance slightly — but steering is always maintained.",
        "Pedal vibration or pulsation during hard braking = ABS working NORMALLY. Do NOT pump the pedal with ABS.",
        "Wheel speed sensor (WSS): Hall effect digital type (modern) or inductive analog (older). One sensor per wheel.",
        "ABS ECU compares all 4 wheel speeds. Rapid deceleration detected at any wheel = commands HCU to release pressure.",
        "ESC or ESP = uses ABS hardware + brakes individual wheels = prevents skid. Mandatory by law for new vehicles in India from 2019.",
      ],
    },
    {
      icon:"🔩", title:"Suspension Type — Quick Identifier for Exam", color:C.blue,
      items:[
        "MacPherson strut: 1 strut (top) + 1 lower control arm = 2 major parts. BUDGET FRONT suspension.",
        "Double wishbone: 2 arms (upper + lower) + separate spring and damper = 4+ parts. PERFORMANCE.",
        "Multi-link: 3-5 separate individual links. PREMIUM REAR suspension (BMW, Mercedes, Hyundai top models).",
        "Leaf spring: flat stacked steel leaves. COMMERCIAL VEHICLES only — all trucks and buses.",
        "Torsion bar: one long steel rod. MAHINDRA FRONT — Scorpio and Thar, some old Jeeps.",
        "Air suspension: rubber bellows filled with air. LUXURY CARS (Mercedes S-class) and HEAVY BUSES.",
        "Golden rule: most common passenger car front suspension = MacPherson Strut. This is the answer every time.",
      ],
    },
    {
      icon:"📋", title:"Most Repeated MPSC Questions — Braking and Suspension", color:C.green,
      items:[
        "Q: Primary purpose of ABS → Prevent wheel lock-up and maintain steering control",
        "Q: Which brake suffers more from brake fade → Drum brake (enclosed, heat trapped inside)",
        "Q: MacPherson strut is used on which axle → Front axle of passenger cars",
        "Q: Camber is viewed from which direction → From FRONT of vehicle",
        "Q: What does shock absorber do → Converts kinetic energy to heat and damps spring oscillations",
        "Q: Braking distance when speed doubles → Quadruples (distance is proportional to v squared)",
        "Q: What fluid is used in hydraulic brakes → DOT 3 or DOT 4 glycol-ether based brake fluid",
        "Q: Tyre cupping or scalloping wear is caused by → Worn or defective shock absorbers",
        "Q: Leaf spring is standard in → Commercial vehicles such as trucks and buses",
        "Q: Parking brake operates on which wheels → Rear wheels via mechanical cable",
        "Q: What is brake bleeding → Removing air bubbles from hydraulic brake lines",
        "Q: Minimum tyre tread depth by MV Rules → 1.6 mm minimum tread depth for road safety",
      ],
    },
  ];
  return (
    <div>
      <STitle icon="⚡" title="EXAM TIPS AND MEMORY TRICKS" sub="Zero-confusion shortcuts for Braking and Suspension" color={C.yellow} />
      <div style={{ display:"grid", gap:14 }}>
        {tricks.map(function(s,i) { return (
          <Box key={i} style={{ borderLeft:"4px solid "+s.color }}>
            <div style={{ display:"flex", gap:12, alignItems:"center", marginBottom:12 }}>
              <span style={{ fontSize:22 }}>{s.icon}</span>
              <span style={{ fontSize:17, color:s.color, fontWeight:700, letterSpacing:2 }}>{s.title}</span>
            </div>
            {s.items.map(function(item,j) { return (
              <div key={j} style={{ display:"flex", gap:10, padding:"7px 0", borderBottom:"1px solid "+C.border+"30", alignItems:"flex-start" }}>
                <span style={{ color:s.color, flexShrink:0, fontSize:11, marginTop:2 }}>▸</span>
                <span style={{ color:C.text, fontSize:13, lineHeight:1.6 }}>{item}</span>
              </div>
            ); })}
          </Box>
        ); })}
      </div>
    </div>
  );
}

// ── MAIN APP ──
var SECTIONS = [
  { id:"intro",      icon:"🛑", label:"Intro and Overview" },
  { id:"drumdisc",   icon:"💿", label:"Drum vs Disc Brakes" },
  { id:"hydraulic",  icon:"💧", label:"Hydraulic System and ABS" },
  { id:"suspension", icon:"🔩", label:"Suspension Types" },
  { id:"alignment",  icon:"📐", label:"Wheel Alignment" },
  { id:"shock",      icon:"🌊", label:"Shock Absorbers and Springs" },
  { id:"formulas",   icon:"🔢", label:"Formula Sheet" },
  { id:"tricks",     icon:"⚡", label:"Tips and Tricks" },
];

export default function App() {
  var [tab, setTab]     = useState("learn");
  var [sec, setSec]     = useState("intro");
  var [qi, setQi]       = useState(0);
  var [sel, setSel]     = useState(null);
  var [exp, setExp]     = useState(false);
  var [done, setDone]   = useState(false);
  var [sc, setSc]       = useState({ c:0, w:0, n:0 });

  var q = QS[qi];
  var acc = sc.n > 0 ? Math.round(sc.c/sc.n*100) : 0;

  function pick(i) {
    if (sel !== null) return;
    setSel(i); setExp(true);
    setSc(function(s){ return { c:s.c+(i===q.ans?1:0), w:s.w+(i!==q.ans?1:0), n:s.n+1 }; });
  }
  function next() {
    if (qi < QS.length-1) { setQi(qi+1); setSel(null); setExp(false); }
    else setDone(true);
  }
  function reset() { setQi(0); setSel(null); setExp(false); setDone(false); setSc({c:0,w:0,n:0}); }

  function renderSection() {
    if (sec==="intro") return <IntroSec />;
    if (sec==="drumdisc") return <DrumDiscSec />;
    if (sec==="hydraulic") return <HydraulicSec />;
    if (sec==="suspension") return <SuspensionSec />;
    if (sec==="alignment") return <AlignmentSec />;
    if (sec==="shock") return <ShockSec />;
    if (sec==="formulas") return <FormulasSec />;
    if (sec==="tricks") return <TricksSec />;
    return null;
  }

  var TABS = [{id:"learn",l:"📖 LEARN"},{id:"practice",l:"📝 PRACTICE"},{id:"formulas",l:"🔢 FORMULAS"},{id:"tricks",l:"⚡ TIPS"}];

  return (
    <div style={{ background:C.bg, minHeight:"100vh", fontFamily:"system-ui,sans-serif", color:C.text }}>
      <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap" rel="stylesheet" />
      <style>{["*{box-sizing:border-box}","::-webkit-scrollbar{width:5px}","::-webkit-scrollbar-thumb{background:#162028;border-radius:3px}"].join("")}</style>

      {/* HEADER */}
      <div style={{ background:"#040206", borderBottom:"1px solid "+C.border, padding:"0 20px" }}>
        <div style={{ maxWidth:920, margin:"0 auto" }}>
          <div style={{ display:"flex", alignItems:"center", gap:16, padding:"18px 0 14px" }}>
            <div style={{ fontSize:36 }}>🛑</div>
            <div>
              <div style={{ fontSize:20, fontWeight:700, color:C.text, letterSpacing:3 }}>BRAKING AND SUSPENSION SYSTEMS</div>
              <div style={{ color:C.muted, fontSize:11, fontFamily:"monospace", marginTop:2 }}>Topic 4 of 12 · Drum · Disc · ABS · MacPherson · Leaf Spring · Alignment</div>
            </div>
            <div style={{ marginLeft:"auto", display:"flex", gap:8 }}>
              <Tag label="8% WEIGHTAGE" color={C.red} />
              <Tag label="8/10 YEARS" color={C.green} />
            </div>
          </div>
          <div style={{ display:"flex" }}>
            {TABS.map(function(t) { return (
              <button key={t.id} onClick={function(){ setTab(t.id); }} style={{
                padding:"11px 22px", border:"none", cursor:"pointer",
                fontFamily:"monospace", fontSize:12, fontWeight:700, background:"transparent",
                color:tab===t.id?C.red:C.muted,
                borderBottom:"3px solid "+(tab===t.id?C.red:"transparent"),
                transition:"all 0.15s",
              }}>{t.l}</button>
            ); })}
          </div>
        </div>
      </div>

      {/* CONTENT */}
      <div style={{ maxWidth:920, margin:"0 auto", padding:"28px 20px" }}>

        {tab==="learn" && (
          <div style={{ display:"grid", gridTemplateColumns:"200px 1fr", gap:20 }}>
            <div>
              <div style={{ fontFamily:"monospace", fontSize:10, color:C.muted, letterSpacing:2, marginBottom:10 }}>SECTIONS</div>
              {SECTIONS.map(function(s) { return (
                <div key={s.id} onClick={function(){ setSec(s.id); }} style={{
                  padding:"9px 12px", borderRadius:8, cursor:"pointer", marginBottom:3,
                  background:sec===s.id?C.red+"15":"transparent",
                  border:"1px solid "+(sec===s.id?C.red+"50":"transparent"),
                  color:sec===s.id?C.red:C.soft,
                  fontSize:12, fontWeight:sec===s.id?600:400, transition:"all 0.12s",
                }}>
                  <span style={{ marginRight:8 }}>{s.icon}</span>{s.label}
                </div>
              ); })}
            </div>
            <div>{renderSection()}</div>
          </div>
        )}

        {tab==="practice" && (
          <div>
            <div style={{ fontSize:20, fontWeight:700, color:C.text, letterSpacing:3, marginBottom:20 }}>PRACTICE — 12 QUESTIONS</div>
            <div style={{ display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:12, marginBottom:24 }}>
              {[{l:"CORRECT",v:sc.c,col:C.green},{l:"WRONG",v:sc.w,col:C.red},{l:"ACCURACY",v:acc+"%",col:C.yellow},{l:"DONE",v:sc.n+"/"+QS.length,col:C.blue}].map(function(s) { return (
                <Box key={s.l} style={{ textAlign:"center", padding:14, borderTop:"3px solid "+s.col }}>
                  <div style={{ fontSize:28, color:s.col, fontWeight:700 }}>{s.v}</div>
                  <div style={{ color:C.muted, fontSize:10, letterSpacing:1.5, textTransform:"uppercase", fontFamily:"monospace", marginTop:3 }}>{s.l}</div>
                </Box>
              ); })}
            </div>

            {done ? (
              <Box glow={C.red} style={{ textAlign:"center", padding:"40px 20px", borderTop:"3px solid "+C.red }}>
                <div style={{ fontSize:60, marginBottom:14 }}>{sc.c>=10?"🏆":sc.c>=7?"🛑":"🔧"}</div>
                <div style={{ fontSize:26, color:C.red, letterSpacing:3, marginBottom:10, fontWeight:700 }}>
                  {sc.c}/{QS.length} — {sc.c>=10?"SAFETY EXPERT!":sc.c>=7?"SOLID KNOWLEDGE":"NEEDS REVISION"}
                </div>
                <div style={{ color:C.soft, maxWidth:420, margin:"0 auto 24px", fontSize:13, lineHeight:1.7 }}>
                  {sc.c>=10?"Outstanding! Ready for Topic 5 — Emission Norms and BS6.":sc.c>=7?"Good. Review ABS working and wheel alignment angles.":"Revise drum vs disc differences, ABS purpose, and suspension types."}
                </div>
                <div style={{ display:"flex", gap:12, justifyContent:"center" }}>
                  <button onClick={reset} style={{ padding:"12px 28px", borderRadius:8, border:"none", background:C.red, color:"#fff", fontWeight:700, cursor:"pointer", fontSize:14 }}>RETRY</button>
                  <button onClick={function(){ setTab("tricks"); }} style={{ padding:"12px 28px", borderRadius:8, border:"1px solid "+C.red, background:"transparent", color:C.red, fontWeight:700, cursor:"pointer", fontSize:14 }}>SEE TIPS</button>
                </div>
              </Box>
            ) : (
              <div>
                <div style={{ display:"flex", gap:8, marginBottom:10 }}>
                  <Tag label={"Q"+(qi+1)+"/"+QS.length} color={C.blue} />
                  <Tag label={q.level} color={q.level==="BASIC"?C.green:q.level==="MEDIUM"?C.yellow:q.level==="HARD"?C.orange:C.purple} />
                  <Tag label={q.topic} color={C.soft} />
                </div>
                <div style={{ height:3, background:C.border, borderRadius:2, marginBottom:20, overflow:"hidden" }}>
                  <div style={{ width:((qi/QS.length)*100)+"%", height:"100%", background:"linear-gradient(90deg,"+C.red+","+C.orange+")", transition:"width 0.3s" }} />
                </div>
                <Box style={{ marginBottom:14, borderLeft:"4px solid "+C.red, padding:"18px 20px" }}>
                  <div style={{ fontSize:15, lineHeight:1.75, fontWeight:500 }}>
                    <span style={{ color:C.red, fontSize:20, marginRight:10, fontWeight:700 }}>Q{qi+1}.</span>{q.q}
                  </div>
                </Box>
                <div style={{ display:"grid", gap:10, marginBottom:18 }}>
                  {q.opts.map(function(opt,i) {
                    var bg=C.card, bdr=C.border, col=C.text, lc=C.muted;
                    if (sel!==null) {
                      if (i===q.ans) { bg=C.green+"15"; bdr=C.green; lc=C.green; }
                      else if (i===sel) { bg=C.red+"15"; bdr=C.red; lc=C.red; col=C.soft; }
                      else { col=C.muted; }
                    }
                    return (
                      <div key={i} onClick={function(){ pick(i); }} style={{ display:"flex", gap:14, alignItems:"flex-start", padding:"13px 16px", borderRadius:10, border:"1.5px solid "+bdr, background:bg, color:col, cursor:sel!==null?"default":"pointer", transition:"all 0.15s" }}>
                        <div style={{ width:28, height:28, borderRadius:6, background:lc+"22", border:"1.5px solid "+lc+"50", display:"flex", alignItems:"center", justifyContent:"center", fontFamily:"monospace", fontSize:12, color:lc, fontWeight:700, flexShrink:0 }}>{["A","B","C","D"][i]}</div>
                        <span style={{ fontSize:13, lineHeight:1.55, paddingTop:4 }}>{opt}</span>
                        {sel!==null && i===q.ans && <span style={{ marginLeft:"auto" }}>✅</span>}
                        {sel!==null && i===sel && i!==q.ans && <span style={{ marginLeft:"auto" }}>❌</span>}
                      </div>
                    );
                  })}
                </div>
                {exp && (
                  <Box style={{ marginBottom:18, borderLeft:"4px solid "+(sel===q.ans?C.green:C.red) }}>
                    <div style={{ fontWeight:700, color:sel===q.ans?C.green:C.red, marginBottom:10, fontSize:14 }}>
                      {sel===q.ans?"✅ CORRECT!":"❌ WRONG — Correct answer: "+["A","B","C","D"][q.ans]}
                    </div>
                    <div style={{ color:C.text, fontSize:13, lineHeight:1.85, whiteSpace:"pre-line", marginBottom:12 }}>{q.exp}</div>
                    <div style={{ padding:"10px 14px", background:C.yellow+"10", borderRadius:8, borderLeft:"3px solid "+C.yellow }}>
                      <span style={{ color:C.yellow, fontWeight:700, fontSize:11, fontFamily:"monospace" }}>EXAM TIP: </span>
                      <span style={{ color:C.text, fontSize:13 }}>{q.tip}</span>
                    </div>
                  </Box>
                )}
                {sel!==null && !done && (
                  <button onClick={next} style={{ width:"100%", padding:15, borderRadius:10, border:"none", background:"linear-gradient(90deg,"+C.red+","+C.orange+")", color:"#fff", fontWeight:700, cursor:"pointer", fontSize:17, letterSpacing:2 }}>
                    {qi<QS.length-1?"NEXT QUESTION →":"FINISH QUIZ"}
                  </button>
                )}
              </div>
            )}
          </div>
        )}

        {tab==="formulas" && <FormulasSec />}
        {tab==="tricks"   && <TricksSec />}
      </div>
    </div>
  );
}